### ISSUE TITLE
Investigate temporary zero-byte archives as .com file placeholders to reserve file IDs

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-toolbelt#14]
This would side-step the part in step 3 where updating version number in `README.md` may have to be deferred:

> (if possible: might need to be done afterwards, if the file download links have yet to be created).

Zero-byte files can be replaced with legit archives when they're ready.

**Comment by Bloke** [comment]
True. We can get away with it at the moment because we only ever add a pair of release files to the server, so we can just add 2 to each value and know we're gonna be okay. But I agree that uploading placeholders would be better.

One caveat: From the Txp UI, it's not (currently) possible to rename a file. So the filename of the zero-byte file would have to exactly match the filename of the eventual file. Otherwise we'd need to do the SFTP dance to rename the old file on the server and then go back to the Txp interface to relink it with the 'missing' file that's just been removed. Failure to do that would show the file size as 0 bytes, since the filesize is only recalculated on upload.

When we eventually merge in the best bits of the adi_file_tab plugin into the Files panel, this will be a bit easier as it'll permit renaming of files.

**Comment by petecooper** [comment]
>From the Txp UI, it's not (currently) possible to rename a file. So the filename of the zero-byte file would have to exactly match the filename of the eventual file.

Yep - absolutely. This could be automated from the branch name, given we use a sensible format.

Definite back burner for now, wanted to mention it before I forgot.

**Comment by petecooper** [comment]
We can come back to this, possibly as part of https://github.com/textpattern/textpattern-toolbelt/issues/12
